export const data = {
        "nodes": [
            {"id": "1", "yes": "9", "no": "2", "value": "¿Te gusta el shonen?", "isLeaf":false},
            {"id": "2", "yes": "6", "no": "3", "value": "¿Te gusta el romance?", "isLeaf":false},
            {"id": "3", "yes": "5", "no": "4", "value": "¿Te gustan los deportes?", "isLeaf":false},
            {"id": "4", "yes": null, "no": null, "value": "Food Wars", "isLeaf":true},
            {"id": "5", "yes": null, "no": null, "value": "Haihyu!", "isLeaf":true},
            {"id": "6", "yes": "8", "no": "7", "value": "¿Te gusta el Gore?", "isLeaf":false},
            {"id": "7", "yes": null, "no": null, "value": "Love is War", "isLeaf":true},
            {"id": "8", "yes": null, "no": null, "value": "School Days", "isLeaf":true},
            {"id": "9", "yes": "19", "no": "10", "value": "¿Te gusta el ecchi?", "isLeaf":false},
            {"id": "10", "yes": "18", "no": "11", "value": "¿Te gustan las lolis?", "isLeaf":false},
            {"id": "11", "yes": "15", "no": "12", "value": "¿Te gustan las protas de pelo rosa?", "isLeaf":false},
            {"id": "12", "yes": "14", "no": "13", "value": "¿Te gusta el romance?", "isLeaf":false},
            {"id": "13", "yes": null, "no": null, "value": "One Punch Man", "isLeaf":true},
            {"id": "14", "yes": null, "no": null, "value": "7 Deadly Sins", "isLeaf":true},
            {"id": "15", "yes": "17", "no": "16", "value": "¿Te gusta el gore?", "isLeaf":false},
            {"id": "16", "yes": null, "no": null, "value": "Rosario + Vampiro", "isLeaf":true},
            {"id": "17", "yes": null, "no": null, "value": "Mirai Nikki", "isLeaf":true},
            {"id": "18", "yes": null, "no": null, "value": "Black Bullet", "isLeaf":true},
            {"id": "19", "yes": "50", "no": "20", "value": "¿Te gustan los protas llorones?", "isLeaf":false},
            {"id": "20", "yes": "36", "no": "21", "value": "¿Te gustan los animes viejos?", "isLeaf":false},
            {"id": "21", "yes": "31", "no": "22", "value": "¿Te gustan los animes largos?", "isLeaf":false},
            {"id": "22", "yes": "28", "no": "23", "value": "¿Te gustan los animes de aventura?", "isLeaf":false},
            {"id": "23", "yes": "27", "no": "24", "value": "¿Te gustan los animes de ciencia?", "isLeaf":false},
            {"id": "24", "yes": "26", "no": "25", "value": "¿Te gustan las buenas animaciones?", "isLeaf":false},
            {"id": "25", "yes": null, "no": null, "value": "Demon Slayer", "isLeaf":true},
            {"id": "26", "yes": null, "no": null, "value": "The Promised Neverland", "isLeaf":true},
            {"id": "27", "yes": null, "no": null, "value": "Dr. Stone", "isLeaf":true},
            {"id": "28", "yes": "30", "no": "29", "value": "¿Te gustan los ánimes de comedia?", "isLeaf":false},
            {"id": "29", "yes": null, "no": null, "value": "Tower of God", "isLeaf":true},
            {"id": "30", "yes": null, "no": null, "value": "Shield Hero", "isLeaf":true},
            {"id": "31", "yes": "35", "no": "32", "value": "¿Te gustan los ánimes de héroes?", "isLeaf":false},
            {"id": "32", "yes": "34", "no": "33", "value": "¿Te gustan las historias elaboradas?", "isLeaf":false},
            {"id": "33", "yes": null, "no": null, "value": "Black Clover", "isLeaf":true},
            {"id": "34", "yes": null, "no": null, "value": "Naruto", "isLeaf":true},
            {"id": "35", "yes": null, "no": null, "value": "Jujutsu Kaisen", "isLeaf":true},
            {"id": "36", "yes": "43", "no": "37", "value": "¿Te gustan los animes de comedia?", "isLeaf":false},
            {"id": "37", "yes": "42", "no": "38", "value": "¿Te gustan el gore?", "isLeaf":false},
            {"id": "39", "yes": "41", "no": "40", "value": "¿Te gustan los animes de suspenso?", "isLeaf":false},
            {"id": "40", "yes": null, "no": null, "value": "Full Metal Alchemist", "isLeaf":true},
            {"id": "41", "yes": null, "no": null, "value": "Death Note", "isLeaf":true},
            {"id": "42", "yes": null, "no": null, "value": "Elfen Lied", "isLeaf":true},
            {"id": "43", "yes": "47", "no": "44", "value": "¿Te gustan los animes con criaturas fantásticas?", "isLeaf":false},
            {"id": "44", "yes": "46", "no": "45", "value": "¿Te gustan los animes de ninjas?", "isLeaf":false},
            {"id": "45", "yes": null, "no": null, "value": "Bleach", "isLeaf":true},
            {"id": "46", "yes": null, "no": null, "value": "Naruto", "isLeaf":true},
            {"id": "47", "yes": "49", "no": "48", "value": "¿Te gustan los animes en transmisión?", "isLeaf":false},
            {"id": "48", "yes": null, "no": null, "value": "Pokemon", "isLeaf":true},
            {"id": "49", "yes": null, "no": null, "value": "Digimon", "isLeaf":true},
            {"id": "50", "yes": "56", "no": "51", "value": "¿Te gustan los animes de comedia?", "isLeaf":false},
            {"id": "51", "yes": "55", "no": "52", "value": "¿Te gustan los animes antiguos?", "isLeaf":false},
            {"id": "52", "yes": "54", "no": "53", "value": "¿Te gustan las protas de cabello rosa?", "isLeaf":false},
            {"id": "53", "yes": null, "no": null, "value": "Attack on Titan", "isLeaf":true},
            {"id": "54", "yes": null, "no": null, "value": "Guilty Crown", "isLeaf":true},
            {"id": "55", "yes": null, "no": null, "value": "Evangelion", "isLeaf":true},
            {"id": "56", "yes": "60", "no": "57", "value": "¿Te gustan los animes gore?", "isLeaf":false},
            {"id": "57", "yes": "59", "no": "58", "value": "¿Te gustan los buenos animes?", "isLeaf":false},
            {"id": "58", "yes": null, "no": null, "value": "Boruto", "isLeaf":true},
            {"id": "59", "yes": null, "no": null, "value": "My Hero Academia", "isLeaf":true},
            {"id": "60", "yes": null, "no": null, "value": "Deadman Wonderland", "isLeaf":true}
        ],
            "root": "1"
}
